export const urls = {
  baseUrl: "http://localhost:8000",
  memberLogin: "http://localhost:8000/member/login",
  createProject: "http://localhost:8000/projects/create-project",
  getAllProject: "http://localhost:8000/projects/get-projects",
  deleteProject: "http://localhost:8000/projects/delete-project",
  editProject: "http://localhost:8000/projects/edit-name",
  fetchAllContents: "http://localhost:8000/projects/fetch-all-contents",
  addColumn: "http://localhost:8000/columns/add",
  moveColumn: "http://localhost:8000/columns/move",
  getEvents: "http://localhost:8000/cal/get",
  saveEvent: "http://localhost:8000/cal/create-event",
  deleteEvent: "http://localhost:8000/cal/delete-event",
  fetchOnline: "http://localhost:8000/fetch-online",
  createCard: "http://localhost:8000/cards/create",
  addSubTask: "http://localhost:8000/sub-tasks/create",
  getSubTasks: "http://localhost:8000/sub-tasks/get",
  deleteSubTask: "http://localhost:8000/sub-tasks/delete",
  updateSubTaskChecked: "http://localhost:8000/sub-tasks/checked",
};
